name: build
# description:
# - Runs Gradle build compiling source code and executing tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'gradle.properties'
      - 'LICENSE'
      - 'README.md'

jobs:
  build:
    name: Run Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Create release')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Restore Gradle Caches
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle.kts') }}-${{ hashFiles('**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-cache-

      - name: Restore Gradle Wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradlew') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-

      - name: Build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: clean build -x signArchives --no-daemon

      - name: Codestyle
        uses: fabiocapasso93/gha-kotlin-linter@v1.0

      - name: Coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./build/reports/jacoco/test/jacocoTestReport.xml
          verbose: true

      - name: FOSSA
        uses: fossa-contrib/fossa-action@v1
        with:
          fossa-api-key: ${{ secrets.FOSSA_API_KEY }}
