name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - gradle.properties
      - LICENSE
      - README.md

jobs:
  build:
    uses: opengoodio/central-workflow/.github/workflows/gradle-lib-build.yml@main
    secrets:
      fossa-api-key: ${{ secrets.FOSSA_API_KEY }}
